# Generated by Django 3.2.5 on 2022-05-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
