# Generated by Django 3.2.5 on 2022-05-23 05:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_auto_20220208_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiongroup',
            name='image',
            field=cloudinary.models.CloudinaryField(default='Some String', max_length=255, verbose_name='image'),
        ),
    ]
