# Generated by Django 3.2.5 on 2022-04-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_alter_disease_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='about',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='image',
        ),
        migrations.AddField(
            model_name='disease',
            name='chemicalcontrol',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='organiccontrol',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='recommendations',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
