# Generated by Django 3.2.5 on 2022-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_auto_20220428_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
